### ISSUE TITLE
Packager fails to build upon npm install

### ISSUE THREAD

**Issue by kennetpostigo** [yeyintkoko/react-native-send-sms#3]
So I installed this package into my app and after it finished installing from npm and I start react-native packager I get the following errors without making the changes in the android folder. The problem persists even after making the changes in the android folder that were instructed from the readme. Here are the errors:

```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /Users/kennetpostigo/Projects/react-native/node_modules/react-native-sms-x/node_modules/react-native/local-cli/core/__fixtures__/files/package.json colli
ative/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /Users/kennetpostigo/Projects/react-native/node_modules/react-native-sms-x/node_modules/react-native/local-cli/core/__fixtures__/files/package.json colli
ative/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/kennetpostigo/Projects/react-native/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:159:13)
    at p.getName.then.name (/Users/kennetpostigo/Projects/react-native/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:134:31)
```

Do you know why this occurs?

**Comment by novotny** [comment]
I have the same issue. Some fix?

**Comment by novotny** [comment]
@kennetpostigo just remove node_modules from this module

**Comment by abdalafer** [comment]
I am experiencing the same issue with no solution so far. It may be related to react-native being the one with issues. What is the highest version of react-native that this package supports? 

I am surprised there is no additional packages for such a common task (sending SMS).

**Comment by yeyintkoko** [comment]
Well. It was build on react native v0.31 or 0.32. Give me some time, I will
upgrate it soon.

**Comment by abdalafer** [comment]
I just downgraded to v0.31 and it continues to give duplicate package issues:
Failed to build DependencyGraph: @providesModule naming collision:
```
  Duplicate module name: String.prototype.es6
  Paths: Documents/reactprojects/AwesomeProject/node_modules/react-native-sms-x/node_modules/react-native/packager/react-packager/src/Resolver/polyfills/String.prototype.es6.js collides with Documents/reactprojects/AwesomeProject/node_modules/react-native/packager/react-packager/src/Resolver/polyfills/String.prototype.es6.js

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: String.prototype.es6
  Paths: Documents/reactprojects/AwesomeProject/node_modules/react-native-sms-x/node_modules/react-native/packager/react-packager/src/Resolver/polyfills/String.prototype.es6.js collides with Documents/reactprojects/AwesomeProject/node_modules/react-native/packager/react-packager/src/Resolver/polyfills/String.prototype.es6.js

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Documents/reactprojects/AwesomeProject/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:155:13)
    at module.getName.then.name (Documents/reactprojects/AwesomeProject/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:115:31)
    at <anonymous>
```

Any suggestions?

**Comment by yeyintkoko** [comment]
Did you try removing node_modules folder and run npm install?

**Comment by abdalafer** [comment]
Which node_modules folder do I delete, is it the one within react-native-sms-x? (`/reactprojects/AwesomeProject/node_modules/react-native-sms-x/node_modules`)

I have removed that one, then went to the root of the react project /reactprojects/AwesomeProject, and did `npm install`,  it does not resolve it. I get a list of duplicate items when I run the application again, it still gives me a long list of duplicate items.

**Comment by yeyintkoko** [comment]
just remove node_modules from this module "node_modules/react-native-sms-x/node_modules" if exists.
